Fashaholic/core/urls.py
from django.urls import path

from .views import (HomeView, ItemDetailView, add_to_cart, remove_from_the_cart, OrderSummary,
                    remove_single_from_the_cart, CheckoutView, PaymentView, AddCouponView,
                    RequestRefundView, add_likes_to_product, CustomerProfileView, add_comment_to_item,
                    SSLPayment, complete, complete_payment)

app_name = 'core'

urlpatterns = [
     path('',
          HomeView.as_view(), name='item_list'),
     path('item_list/<category_name>/',
          HomeView.as_view(), name='item_list_by_category'),
     path('checkout/',
          CheckoutView.as_view(), name='checkout'),
     path('payment/<payment_option>/',
          PaymentView.as_view(), name="payment"),
     path('products/<slug>/',
          ItemDetailView.as_view(), name='products'),
     path('order_summary/',
          OrderSummary.as_view(), name='order_summary'),
     path('customer_profile/',
          CustomerProfileView.as_view(), name='customer_profile'),
     path('add_to_cart/<slug>/',
          add_to_cart, name='add_to_cart'),
     path('remove_from_the_cart/<slug>/',
          remove_from_the_cart, name='remove_from_the_cart'),
     path('remove_single_from_the_cart/<slug>/',
          remove_single_from_the_cart, name='remove_single_from_the_cart'),
     path('add_coupon/',
          AddCouponView.as_view(), name="add_coupon"),
     path('request_refund/',
          RequestRefundView.as_view(), name="request_refund"),
     path('add_likes_to_product/<slug>/',
          add_likes_to_product, name="likes"),
     path('add_comment_to_item/<slug>/',
          add_comment_to_item, name="comments"),
     path('ssl_payment/', SSLPayment.as_view(), name='ssl_payment'),
     path('complete/', complete, name='complete'),
     path('complete_payment/<tran_id>/<payment_type>/',
          complete_payment, name='complete_payment'),

]

Fashaholic/djangoecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fashaholic/core/forms.py
from django import forms
from django.utils import six
from django.utils.encoding import smart_text
from django.utils.six import python_2_unicode_compatible
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from .models import Comment

CHOICE_FIELDS = (
    ('S', 'Stripe'),
    ('P', 'Paypal'),
    ('SSL', 'SSL Ecommerce')
)


class CheckoutForm(forms.Form):
    # Shipping information
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_zip = forms.CharField(required=False)
    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)

    # Billing information
    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    # Payment Method
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=CHOICE_FIELDS)


class CouponForm(forms.Form):
    coupon_code = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control",
        'placeholder': 'Promo Code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby':"basic-addon2"
        }
    ))


class RefundForm(forms.Form):
    reference_code = forms.CharField(max_length=20)
    reason = forms.CharField(widget=forms.Textarea(attrs={
        "row": 2
    }))
    email = forms.EmailField()


class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(attrs={
        "cols": 200,
        "rows": 3,
        "class": "form-control",
        "placeholder": "Write A Comment"
    }))

Fashaholic/templates/any_form.html
<main>
    <div class="container">
      <section class="mb-4">
        <div class="row wow fadeIn">
          <div class='col-6 offset-3'>
              <form>
                   {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary">
                      Submit
                  </button>
                </form>
          </div>
        </div>
      </section>
    </div>
 </main>

Fashaholic/templates/base.html
<!DOCTYPE html>
<html lang="en">

    {% include 'head.html' %}
    {% include 'navbar.html' %}
    <body>
        <div class="mt-1 pt-1">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>


        {% block content %}
        {% endblock %}

        {% block extra_body %}
        {% endblock %}

        {% include 'script.html' %}
        {% block extra_scripts %}
        {% endblock extra_scripts %}

    </body>
</html>

Fashaholic/templates/category.html
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mt-3 mb-2">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
              {% for cat in categories %}
            <li class="nav-item">
              <a class="nav-link" href="{{cat.get_absolute_url}}">{{cat.category}}</a>
            </li>
              {% endfor %}
          </ul>
          <!-- Links -->

          <form class="form-inline" method="get" action="/">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" name="key" placeholder="Search by name/category" aria-label="Search" style="color: #FFFFFF;">
                <button type="submit" style="background-color: #555555;">Search</button>
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>

Fashaholic/templates/checkout-page.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<main >
  <div class="container wow fadeIn">
    <h2 class="my-5 h2 text-left">Checkout form</h2>
    <div class="row">
      <div class="col-md-8 mb-4">
        <div class="card">
          <form method="POST" class="card-body">
            {% csrf_token %}
            <!--Shipping Information Fill Up-->
            <h3>Shipping address</h3>

            <div class='hideable_shipping_form'>

              <div class="md-form mb-5">
                <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                <label for="shipping_address" class="">Address</label>
              </div>

              <div class="md-form mb-5">
                <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                <label for="shipping_address2" class="">Address 2 (optional)</label>
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.shipping_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="shipping_zip">Zip</label>
                  <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>
              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
                <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
              </div>

            </div>

            {% if default_shipping_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
              <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
            </div>
            {% endif %}

            <hr>
            <!--Billing Information Fill Up-->
            <h3>Billing address</h3>

            <div class='hideable_billing_form'>
              <div class="md-form mb-5">
                <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address' class='form-control' />
                <label for="billing_address" class="">Address</label>
              </div>

              <div class="md-form mb-5">
                <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2' class='form-control' />
                <label for="billing_address2" class="">Address 2 (optional)</label>
              </div>

              <div class="row">
                <div class="col-lg-4 col-md-12 mb-4">
                  <label for="country">Country</label>
                  {{ form.billing_country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>
                </div>

                <div class="col-lg-4 col-md-6 mb-4">
                  <label for="billing_zip">Zip</label>
                  <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>
                </div>

              </div>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
              </div>

            </div>

            {% if default_billing_address %}
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
              <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
            </div>
            {% endif %}
            <hr>

            <!--Payment Information Fill Up-->
            <h3>Payment option</h3>

            <div class="d-block my-3">
              {% for value, name in form.fields.payment_option.choices %}
              <div class="custom-control custom-radio">
                <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
              </div>
              {% endfor %}
            </div>

            <hr class="mb-4">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

          </form>

        </div>

      </div>

      <div class="col-md-4 mb-4">
        {% include "order_snippet.html" %}
      </div>

    </div>

  </div>
</main>
  
{% endblock %}

  {% block extra_scripts %}
  <script>
    const hideable_shipping_form = $(".hideable_shipping_form")
    const hideable_billing_form = $(".hideable_billing_form")
    const use_default_shipping = document.querySelector("input[name=use_default_shipping")
    const use_default_billing = document.querySelector("input[name=use_default_billing]")
    const same_billing_address = document.querySelector("input[name=same_billing_address]")
    if(use_default_shipping){
      use_default_shipping.addEventListener(
      'change', function() {
        if(this.checked){
          hideable_shipping_form.hide()
        }
        else{
          hideable_shipping_form.show()
        }
      }
    )
    }
    if(use_default_billing){
      use_default_billing.addEventListener(
      'change', function() {
        if(this.checked){
          hideable_billing_form.hide()
        }
        else{
          hideable_billing_form.show()
        }
      }
    )
    }

    same_billing_address.addEventListener(
      'change', function() {
        if(this.checked){
          hideable_billing_form.hide()
        }
        else{
          hideable_billing_form.show()
        }
      }
    )
  </script>
{% endblock extra_scripts %}

Fashaholic/templates/complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="5; url={% url 'core:item_list' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <div class="mt-5 pt-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>
</body>
</html>

Fashaholic/templates/customer_profile.html
{% extends 'base.html' %}
{% block content %}
<h2 class="h2 text-center">Order History</h2>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Order</th>
      <th scope="col">Date</th>
      <th scope="col">Items</th>
      <th scope="col">Total(BDT)</th>
      <th scope="col">Reference Code</th>
      <th scope="col">Request Refund</th>
    </tr>
  </thead>
  <tbody>
    <tr>
        {% for order in orders %}
        <th><strong>{{forloop.counter}}</strong></th>
        <td><strong>{{order.ordered_date|date:'Y/m/d'}}</strong></td>
      <td>
          {% for item in order.items.all %}
          <li style="list-style-type:none;">
              <strong>{{item}}</strong>
          </li>
          {% endfor %}

      </td>
        <td><strong>{{order.payment.amount}}</strong></td>
        <td><strong>{{order.reference_code}}</strong></td>
        {% if order.refund_requested %}
        <td><b><strong style="color:red;">Refund Requested</strong></b></td>
        {% elif order.refund_granted %}
        <td><b><strong style="color:green;">Refund Granted</strong></b></td>
        {% else %}
        <td><a style="color:blue;" href="/request_refund/"><b><strong>Refund</strong></b></a></td>
        {% endif %}
    </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock content %}

Fashaholic/templates/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="E-commerce website that makes use of various recommendation algorithms to suggest products to users">
    <title> My website {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">

    <style type="text/css">
      html,
      body,
      header,
      .carousel {
        height: 60vh;
      }

      @media (max-width: 740px) {

        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }

      @media (min-width: 800px) and (max-width: 850px) {

        html,
        body,
        header,
        .carousel {
          height: 100vh;
        }
      }



    </style>
  </head>

Fashaholic/templates/navbar.html
{% load cart_template_tags %}
<nav class="mb-1 navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      <img src="https://t4.ftcdn.net/jpg/02/98/50/73/360_F_298507373_jSqa30ZgynPwwT2CsdLgVkuwczAE18db.jpg" alt="..." height="36">
    </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
    aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
    {% if not request.user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/accounts/login/">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/accounts/signup/">Sign Up</a>
      </li>
    </ul>
    {% else %}
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="/">Home
        </a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="/accounts/password/change/">Reset Password
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/accounts/logout/">Logout</a>
      </li>
      <li class="nav-item">
      <a class="nav-link" href="/request_refund/">Request Refund</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
        <a class="nav-link waves-effect" href="/order_summary/">{{ request.user|cart_item_count }}
          <i class="fas fa-shopping-cart"></i>
        </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/customer_profile/">{{request.user}}
          <span class="sr-only">(current)</span>
        </a>
      </li>
      </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
      {% endif %}
    </ul>
  </div>
</nav>

Fashaholic/templates/order_snippet.html
<div class="col-md-12 mb-4">
  <h4 class="d-flex justify-content-between align-items-center mb-3">
  <span class="text-muted">Your cart</span>
  <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
  </h4>
  <ul class="list-group mb-3 z-depth-1">
  {% for order_item in orders.items.all %}
  <li class="list-group-item d-flex justify-content-between lh-condensed">
      <div>
      <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.item_name}}</h6>
      <small class="text-muted">{{ order_item.item.description|truncatewords:10}}</small>
      </div>
      <span class="text-muted">{{ order_item.get_final_price }}</span>
  </li>
  {% endfor %}
  {% if orders.coupon %}
  <li class="list-group-item d-flex justify-content-between bg-light">
      <div class="text-success">
      <h6 class="my-0">{{orders.coupon.coupon}}</h6>
      <small>{{ orders.coupon.code }}</small>
      </div>
      <span class="text-success">-{{ orders.coupon.amount }}</span>
  </li>
  {% endif %}
  <li class="list-group-item d-flex justify-content-between">
      <span>Total (BDT)</span>
      <strong>{{ orders.get_total }}</strong>
  </li>
  </ul>

  {% if DISPLAY_COUPON_FORM %}
  <form class="card p-2" action="{% url 'core:add_coupon' %}" method="POST">
      <p>Promo Code = Django</p>
      {% csrf_token %}
      <div class="input-group">
          {{ coupon_form.coupon_code }}
          <div class="input-group-append">
          <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
          </div>
      </div>
  </form>
  {% endif %}

</div>

Fashaholic/templates/product-page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load static %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{object.item_image.url}}" class="img-fluid" alt="" style ="height:500px; object-fit:cover;">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="{{object.item_category.get_absolute_url}}">
                <span class="badge purple mr-1">{{object.item_category}}</span>
              </a>

              <span>
                {{object.item_name}}
              </span>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                  <del>{{object.price}}</del>
                </span>
              <span>{{object.discount_price}}</span>
              {% else %}
              <span>{{object.price}}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{object.description}}</p>


            <a href="{% url 'core:likes' slug=object.slug %}" class="btn btn-primary btn-md my-0 p">
                  <i class="fas fa-heart mr-1">  {{object.likes.count}}</i>
                </a>

           <a href="{{object.get_add_to_cart}}" class="btn btn-primary btn-md my-0 p">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
           </a>

           <a href="{{object.remove_from_the_cart}}" class="btn btn-danger btn-md my-0 p">Remove from the cart
            <i class="fas fa-shopping-cart ml-1"></i>
         </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Similar products recommendation-->
      <hr style="height:10px;border:none;color:#333;background-color:#333;" />
      <h1 align="center">SIMILAR PRODUCTS</h1>
      <hr style="height:10px;border:none;color:#333;background-color:#333;" />

      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
            {% for item in rec %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card" style = "height:420px; object-fit:cover; object-position: top;">
              <div class="view overlay">
                <img src="{{item.item_image.url}}" class="card-img-top"
                  alt="">
                <a href="{{item.get_absolute_url}}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <div class="card-body text-center">
                <a href="{{item.get_absolute_url}}" class="dark-grey-text">
                  <h5>{{item.item_category}}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{item.get_absolute_url}}" class="dark-grey-text">{{item.item_name}}</a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>{{item.price}}</strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
          {% if object_list.count == 0 %}
          <div>
            <h1 style="text-align: center;">No items found</h1>
          </div>
          {% endif %}
      </div>
      </section>
      <!--Similar products recommendation-->

      <!--Product comments-->
      <hr style="height:10px;border:none;color:#333;background-color:#333;" />
        <div class="container">
            {% if comments.count != 0 %}
            <div class="row">
                <p>Total Comments {{comments.count}}</p>
            </div>
            {% endif %}
            <div class="row">
                <ul class="list-unstyled">
                    {% if comments %}
                    {% for comment in comments %}
                    <hr>
                    <li class="media">
                        <div class="media-body">
                            <h6 class="lead card-text"> Posted by: {{comment.user.username}}</h6>
                            <p class="lead card-text">{{comment}}</p>
                            <p class="lead card-text">Posted on: <strong>{{comment.date}}</strong></p>

                        </div>
                    </li>
                    {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
        {% if request.user.is_authenticated %}
        <h4 class="my-4">Leave a comment</h4>
      <form action="{% url 'core:comments' slug=object.slug %}" method="post">
           {% csrf_token %}
      <!--{{ form|crispy }}-->
          <div class="form-group">
              <textarea name="comment" cols="200" rows="3" class="form-control" placeholder="Write A Comment" required="" id="id_comment"></textarea>
          </div>
            <button type="submit" class="btn btn-primary">
              Post
          </button>
        </form>
        {% else %}
        <div class="row mt-1 mb-2">
            <a class="btn btn-danger text-black" type="button" href="/accounts/login/">Login to comment</a>
        </div>
        {% endif %}
        <!--Product comments-->

    </div>
  </main>

{% endblock %}

Fashaholic/templates/script.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>

Fashaholic/templates/ssl_payment.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row mt-3">
        <h4>SSL Payment</h4>
    </div>
</div>
{% endblock content %}